= Tasks

== Themes

=== Data manipulation

==== Specification of Task 1

1. Создать базу данных стран. Подключиться к базе данных.
Создать таблицу для хранения данных о странах со следующими полями:
- название
- численность населения (млн.)
- площадь (тыс. кв. км.)
- государственный язык
2. Заполнить таблицу данными (10+ стран).
3. Написать запрос, выбирающий из таблицы все страны с населением выше 50 млн. человек
4. Написать запрос, выбирающий из таблицы все страны, отсортированные по возрастанию численности территории
5. Написать запрос, выбирающий из таблицы суммарное население пяти самых маленьких стран
6. Написать запрос, заменяющий государственный язык одной из стран на другой.
7. Написать запрос, удаляющий страну с наибольшим населением

==== Specification of Task 2

1. Создать базу данных книг. Подключиться к базе данных.
2. Создать таблицу для хранения данных о книгах со следующими полями:
    - идентификатор (id)
    - название
    - жанр
    - год издания
    - id автора
3. Создать таблицу авторов книг со следующими полями:
     - идентификатор (id)
     - имя
     - фамилия
     - страна
4. Сделать первичным ключом каждой таблицы идентификатор.
5. Добавить идентификаторам авто-инкрементирование.
6. В таблице книг сделать внешний ключ на таблицу авторов (поле id автора)
7. Заполнить таблицу авторов данными (5+ записей)
8. Заполнить таблицу книг данными (10+ записей)
9. Написать запрос, выбирающий: название книги и имя автора, отсортированные по году издания книги в возрастающем порядке.
Написать тот же запрос, но для убывающего порядка.
10. Написать запрос, выбирающий количество книг у заданного автора.

=== Нормализация. Joins. Группировки.

В базе данных хранится информация о книгах и их авторах.
Перу одного автора может принадлежать множество книг.
Над одной и той же книгой могло работать несколько авторов.
Разработать схему базы данных для данного условия.
Во всех таблицах должен быть id с автоинкрементом.

В таблице книг должна храниться следующая информация о книгах:

- название
- количество страниц
- жанр

В таблице авторов должна хранится следующая информация об авторах:

- имя
- дата рождения
- национальность

Добавить записи в таблицу книг (10+) и таблицу авторов (5+).

Написать следующие запросы:

1. Выбрать из базы данных имена авторов с названиями написанных ими книг.
Назвать поля результирующей таблицы book_author и book_name.
2. Выбрать из таблицы все книги авторов выбранной национальности.
3. Выбрать из таблицы все книги, авторы которых родились после 1900 года.
4. Удалить из таблицы данных книгу с заданным названием.
5. Выбрать из таблицы: имя автора, национальность и среднее количество написанных им страниц, упорядочить по году рождения автора.
6. Выбрать из таблицы: имя автора, национальность и среднее количество написанных им страниц, где среднее число страниц больше 300.
7. * Выбрать из таблицы данные в виде: автор, ср. число страниц для всех авторов, среднее количество написанных страниц которых выше среднего количества страниц, написанных всеми авторами.

